# Generated by Django 2.0.6 on 2018-06-09 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_testparticipant_testparticipantanswers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testparticipant',
            name='participant_name',
        ),
        migrations.RemoveField(
            model_name='testparticipant',
            name='participant_surname',
        ),
        migrations.AddField(
            model_name='testparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
